version: "3.8"

services:
  # client:
  #   build: 
  #     context: .
  #     dockerfile: docker/client/Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /app/node_modules
  #     - /app/.next
  #     - ./client:/app
  #   env_file: ./client/.env
    
  server:
    build: 
      context: .
      dockerfile: docker/server/Dockerfile.dev
    depends_on:
      - redis
      - postgres
    volumes:
      - ./server:/app
      - ./docker:/app/docker
    env_file:
      - ./server/.env
    networks:
      - devto-app
    restart: unless-stopped
    command: ./docker/server/run.dev.sh

  redis:
    build: 
      context: docker/redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - devto-app

  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=devto
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devto-app
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    networks:
      - devto-app
    restart: unless-stopped



networks:
  devto-app:
    driver: bridge


volumes:
  redis-data:
    driver: local
  pg-data:
    driver: local
  pg-admin:
    driver: local