export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SET_USER = "SET_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const LOGOUT = "LOGOUT";

export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const GET_ALL_USER_ARTICLES = "GET_ALL_USER_ARTICLES";
export const GET_USER_ARTICLE_BY_ID = "GET_USER_ARTICLE_BY_ID";
export const GET_ARTICLE_BY_SLUG = "GET_ARTICLE_BY_SLUG";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const CLAP_ARTICLE = "CLAP_ARTICLE";
export const COMMENT_ARTICLE = "COMMENT_ARTICLE";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
